### PR TITLE
go/consensus/tendermint/apps/governance: Ensure upgrade is in progress

### LINKED ISSUE #4070: Governance should check if upgrade was applied
The governance service currently performs an `EnsureCompatible` sanity check which fails in case someone would manually cancel the upgrade descriptor installed by governance. But the compatibility check only checks the protocol versions and not other properties like upgrade handlers.

It should instead check if the appropriate upgrade descriptor is installed and has been executed and fail in case this is not the case, stopping the node for upgrade.

### PR DESCRIPTION
**Pull request by kostko**
Fixes #4070

### CODE REVIEW

File: go/consensus/tendermint/apps/governance/governance.go [hunk 1]
```diff
@@ -149,12 +149,36 @@ func (app *governanceApplication) BeginBlock(ctx *api.Context, request types.Req
...
+			if !pu.HasStage(upgrade.UpgradeStageStartup) {
+				ctx.Logger().Error("upgrade pending but not being applied",
+					"handler", ud.Handler,
+					"epoch", ud.Epoch,
+					"upgrade_height", pu.UpgradeHeight,
+					"last_completed_stage", pu.LastCompletedStage,
+				)
+				return upgrade.ErrStopForUpgrade
+			}
+		case upgrade.ErrUpgradeNotFound:
```
Comment (ptrus) [inline go/consensus/tendermint/apps/governance/governance.go:166]: This prevents locally canceling a consensus upgrade (2/3+ nodes locally canceling an upcoming pending upgrade), but i think this is fine as in case an already accepted upgrade needs to be reverted/aborted manual intervention is needed anyway so this can be achieved otherwise (e.g. stopping the nodes at the upgrade epoch and doing a "dump-restore" without the upgrade)

**Review by ptrus — APPROVED** [review]

File: go/consensus/tendermint/apps/governance/governance.go (hunk 1 above)
Comment (kostko) [reply go/consensus/tendermint/apps/governance/governance.go:166]: Yeah, especially since there is also an option to cancel an upgrade via governance (should we consider reducing `upgrade_cancel_min_epoch_diff`?).

Comment (ptrus) [reply go/consensus/tendermint/apps/governance/governance.go:166]: Yeah that would make sense
