### PR TITLE
go/runtime/client: Fail SubmitTx early for unsupported runtimes

### LINKED ISSUE #4202: Runtime SubmitTx should fail for unsupported runtimes
Currently the `SubmitTx` family of methods will work even when specifying runtimes which are not configured as supported by the node. This will result in the transaction being submitted via the P2P network, but the client will be unable to see any results so the blocking variants will just block forever (or until a timeout).

The correct thing to do would be to fail SubmitTx early.

### PR DESCRIPTION
**Pull request by kostko**
Fixes #4202 

Make sure that the runtime is actually among the supported runtimes as
otherwise we will not be able to actually get any results back.

### CODE REVIEW

File: go/runtime/client/client.go [hunk 1]
```diff
@@ -85,6 +85,12 @@ func (c *runtimeClient) submitTx(ctx context.Context, request *api.SubmitTxReque
 		return nil, fmt.Errorf("client: cannot submit transaction, p2p disabled")
 	}
 
+	// Make sure that the runtime is actually among the supported runtimes for this node as
+	// otherwise we will not be able to actually get any results back.
+	if _, err := c.common.runtimeRegistry.GetRuntime(request.RuntimeID); err != nil {
```
Comment (ptrus) [inline go/runtime/client/client.go:90]: Could add a test for this, maybe include it in one of the exiting e2e tests?

Comment (kostko) [reply go/runtime/client/client.go:90]: Added.

**Review by ptrus — APPROVED** [review]
